import {
  LucideAlertCircle as AlertCircle,
  LucideAlertTriangle as AlertTriangle,
  LucideArrowLeft as ArrowLeft,
  LucideBriefcase as Briefcase,
  LucideCalendar as Calendar,
  LucideCalendarDays as CalendarDays,
  LucideCalendarPlus as CalendarPlus,
  LucideCamera as Camera,
  LucideCat as Cat,
  LucideCheck as Check,
  LucideCheckCircle as CheckCircle,
  LucideCircleQuestionMark as CircleQuestionMark,
  LucideCirclePause as CirclePause,
  LucideClock as Clock,
  LucideCpu as Cpu,
  LucideCross as Cross,
  LucideDog as Dog,
  LucideDollarSign as DollarSign,
  LucideEye as Eye,
  LucideEyeOff as EyeOff,
  LucideFileText as FileText,
  LucideHome as Home,
  LucideLayoutDashboard as LayoutDashboard,
  LucideLock as Lock,
  LucideLogOut as LogOut,
  LucideMail as Mail,
  LucideMapPin as MapPin,
  LucideMenu as Menu,
  LucidePawPrint as PawPrint,
  LucidePencil as Pencil,
  LucidePhone as Phone,
  LucidePill as Pill,
  LucidePlus as Plus,
  LucidePlusSquare as PlusSquare,
  LucideReceipt as Receipt,
  LucideSave as Save,
  LucideScissors as Scissors,
  LucideSearch as Search,
  LucideShield as Shield,
  LucideStethoscope as Stethoscope,
  LucideTrash2 as Trash2,
  LucideTriangleAlert as TriangleAlert,
  LucideUser as User,
  LucideUserCog as UserCog,
  LucideUsers as Users,
  LucideX as X,
  LucideXCircle as XCircle
} from '@lucide/angular';

export const LUCIDE_ICONS = {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  Briefcase,
  Calendar,
  CalendarDays,
  CalendarPlus,
  Camera,
  Cat,
  Check,
  CheckCircle,
  CircleQuestionMark,
  CirclePause,
  Clock,
  Cpu,
  Cross,
  Dog,
  DollarSign,
  Eye,
  EyeOff,
  FileText,
  Home,
  LayoutDashboard,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Menu,
  PawPrint,
  Pencil,
  Phone,
  Pill,
  Plus,
  PlusSquare,
  Receipt,
  Save,
  Scissors,
  Search,
  Shield,
  Stethoscope,
  Trash2,
  TriangleAlert,
  User,
  UserCog,
  Users,
  X,
  XCircle
}
